In [1]:
import pandas as pd
import numpy as np

In [97]:
df =pd.read_csv('train.csv')
print(df)
print(df.index)
print(df.columns)
print(df.shape)
print(df.size) #row*column
print(df.values)
print(df.ndim)
print(df.dtypes)
# df.T #transpose

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]
RangeIndex(start=0, stop=891, step=1)
Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')
(891, 12)
10692
[[1 0 3 ... 7.25 nan 'S']
 [2 1 1 ... 71.2833 'C85' 'C']
 [3 1 3 ... 7.925 nan 'S']
 ...
 [889 0 3 ... 23.45 nan 'S']
 [890 1 1 ... 30.0 'C148' 'C']
 [891 0 3 ... 7.75 nan 'Q']]
2
PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [88]:
print(df['Pclass'])

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [89]:
print(pd.DataFrame(df[['Pclass' , 'Age']]))

     Pclass   Age
0         3  22.0
1         1  38.0
2         3  26.0
3         1  35.0
4         3  35.0
..      ...   ...
886       2  27.0
887       1  19.0
888       3   NaN
889       1  26.0
890       3  32.0

[891 rows x 2 columns]

In [44]:
print(df[df['Age']>18])

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
885          886         0       3
886          887         0       2
887          888         1       1
889          890         1       1
890          891         0       3

                                                  Name   Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris  Male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  Male  38.0      1
2                               Heikkinen, Miss. Laina  Male  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  Male  35.0      1
4                             Allen, Mr. William Henry  Male  35.0      0
..                                                 ...   ...   ...    ...
885               Rice, Mrs. William (Margaret Norton)  Male  39.0      0
886                              Montvila, Rev. Juozas  Male  27.0      0
887                       Graham, Miss. Margaret Edith  Male  19.0      0
889                              Behr, Mr. Karl Howell  Male  26.0      0
890                                Dooley, Mr. Patrick  Male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
885      5            382652  29.1250   NaN        Q
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[575 rows x 12 columns]

In [90]:
(df['Age']>18) & (df['Sex']=='male')

0       True
1      False
2      False
3      False
4       True
       ...
886     True
887    False
888    False
889     True
890     True
Length: 891, dtype: bool

In [100]:
print(df[df['Sex']=='female'])

                                                    PassengerId  Survived  \
Name
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1
Heikkinen, Miss. Laina                                        3         1
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)             9         1
Nasser, Mrs. Nicholas (Adele Achem)                          10         1
...                                                         ...       ...
Shelley, Mrs. William (Imanita Parrish Hall)                881         1
Dahlberg, Miss. Gerda Ulrika                                883         0
Rice, Mrs. William (Margaret Norton)                        886         0
Graham, Miss. Margaret Edith                                888         1
Johnston, Miss. Catherine Helen "Carrie"                    889         0

                                                    Pclass     Sex   Age  \
Name
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0
Heikkinen, Miss. Laina                                   3  female  26.0
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)        3  female  27.0
Nasser, Mrs. Nicholas (Adele Achem)                      2  female  14.0
...                                                    ...     ...   ...
Shelley, Mrs. William (Imanita Parrish Hall)             2  female  25.0
Dahlberg, Miss. Gerda Ulrika                             3  female  22.0
Rice, Mrs. William (Margaret Norton)                     3  female  39.0
Graham, Miss. Margaret Edith                             1  female  19.0
Johnston, Miss. Catherine Helen "Carrie"                 3  female   NaN

                                                    SibSp  Parch  \
Name
Cumings, Mrs. John Bradley (Florence Briggs Tha...      1      0
Heikkinen, Miss. Laina                                  0      0
Futrelle, Mrs. Jacques Heath (Lily May Peel)            1      0
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)       0      2
Nasser, Mrs. Nicholas (Adele Achem)                     1      0
...                                                   ...    ...
Shelley, Mrs. William (Imanita Parrish Hall)            0      1
Dahlberg, Miss. Gerda Ulrika                            0      0
Rice, Mrs. William (Margaret Norton)                    0      5
Graham, Miss. Margaret Edith                            0      0
Johnston, Miss. Catherine Helen "Carrie"                1      2

                                                              Ticket     Fare  \
Name
Cumings, Mrs. John Bradley (Florence Briggs Tha...          PC 17599  71.2833
Heikkinen, Miss. Laina                              STON/O2. 3101282   7.9250
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  113803  53.1000
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)             347742  11.1333
Nasser, Mrs. Nicholas (Adele Achem)                           237736  30.0708
...                                                              ...      ...
Shelley, Mrs. William (Imanita Parrish Hall)                  230433  26.0000
Dahlberg, Miss. Gerda Ulrika                                    7552  10.5167
Rice, Mrs. William (Margaret Norton)                          382652  29.1250
Graham, Miss. Margaret Edith                                  112053  30.0000
Johnston, Miss. Catherine Helen "Carrie"                  W./C. 6607  23.4500

                                                   Cabin Embarked
Name
Cumings, Mrs. John Bradley (Florence Briggs Tha...   C85        C
Heikkinen, Miss. Laina                               NaN        S
Futrelle, Mrs. Jacques Heath (Lily May Peel)        C123        S
Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)    NaN        S
Nasser, Mrs. Nicholas (Adele Achem)                  NaN        C
...                                                  ...      ...
Shelley, Mrs. William (Imanita Parrish Hall)         NaN        S
Dahlberg, Miss. Gerda Ulrika                         NaN        S
Rice, Mrs. William (Margaret Norton)                 NaN        Q
Graham, Miss. Margaret Edith                         B42        S
Johnston, Miss. Catherine Helen "Carrie"             NaN        S

[314 rows x 11 columns]

In [101]:
df.iloc[2,2]

3

In [102]:
df.iloc[:10 , 3:9]

,Sex,Age,SibSp,Parch,Ticket,Fare
Name,,,,,,
"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833
"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500
"Moran, Mr. James",male,NaN,0,0,330877,8.4583
"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625
"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750
"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333
"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708

In [103]:
print(df)

                                                    PassengerId  Survived  \
Name
Braund, Mr. Owen Harris                                       1         0
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1
Heikkinen, Miss. Laina                                        3         1
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1
Allen, Mr. William Henry                                      5         0
...                                                         ...       ...
Montvila, Rev. Juozas                                       887         0
Graham, Miss. Margaret Edith                                888         1
Johnston, Miss. Catherine Helen "Carrie"                    889         0
Behr, Mr. Karl Howell                                       890         1
Dooley, Mr. Patrick                                         891         0

                                                    Pclass     Sex   Age  \
Name
Braund, Mr. Owen Harris                                  3    male  22.0
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0
Heikkinen, Miss. Laina                                   3  female  26.0
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0
Allen, Mr. William Henry                                 3    male  35.0
...                                                    ...     ...   ...
Montvila, Rev. Juozas                                    2    male  27.0
Graham, Miss. Margaret Edith                             1  female  19.0
Johnston, Miss. Catherine Helen "Carrie"                 3  female   NaN
Behr, Mr. Karl Howell                                    1    male  26.0
Dooley, Mr. Patrick                                      3    male  32.0

                                                    SibSp  Parch  \
Name
Braund, Mr. Owen Harris                                 1      0
Cumings, Mrs. John Bradley (Florence Briggs Tha...      1      0
Heikkinen, Miss. Laina                                  0      0
Futrelle, Mrs. Jacques Heath (Lily May Peel)            1      0
Allen, Mr. William Henry                                0      0
...                                                   ...    ...
Montvila, Rev. Juozas                                   0      0
Graham, Miss. Margaret Edith                            0      0
Johnston, Miss. Catherine Helen "Carrie"                1      2
Behr, Mr. Karl Howell                                   0      0
Dooley, Mr. Patrick                                     0      0

                                                              Ticket     Fare  \
Name
Braund, Mr. Owen Harris                                    A/5 21171   7.2500
Cumings, Mrs. John Bradley (Florence Briggs Tha...          PC 17599  71.2833
Heikkinen, Miss. Laina                              STON/O2. 3101282   7.9250
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  113803  53.1000
Allen, Mr. William Henry                                      373450   8.0500
...                                                              ...      ...
Montvila, Rev. Juozas                                         211536  13.0000
Graham, Miss. Margaret Edith                                  112053  30.0000
Johnston, Miss. Catherine Helen "Carrie"                  W./C. 6607  23.4500
Behr, Mr. Karl Howell                                         111369  30.0000
Dooley, Mr. Patrick                                           370376   7.7500

                                                   Cabin Embarked
Name
Braund, Mr. Owen Harris                              NaN        S
Cumings, Mrs. John Bradley (Florence Briggs Tha...   C85        C
Heikkinen, Miss. Laina                               NaN        S
Futrelle, Mrs. Jacques Heath (Lily May Peel)        C123        S
Allen, Mr. William Henry                             NaN        S
...                                                  ...      ...
Montvila, Rev. Juozas                                NaN        S
Graham, Miss. Margaret Edith                         B42        S
Johnston, Miss. Catherine Helen "Carrie"             NaN        S
Behr, Mr. Karl Howell                               C148        C
Dooley, Mr. Patrick                                  NaN        Q

[891 rows x 11 columns]

In [106]:
df.loc['Braund, Mr. Owen Harris']

PassengerId            1
Survived               0
Pclass                 3
Sex                 male
Age                   22
SibSp                  1
Parch                  0
Ticket         A/5 21171
Fare                7.25
Cabin                NaN
Embarked               S
Name: Braund, Mr. Owen Harris, dtype: object

In [108]:
df.loc['Braund, Mr. Owen Harris':'Nasser, Mrs. Nicholas (Adele Achem)',:'Ticket']

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket
Name,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450
"Moran, Mr. James",6,0,3,male,NaN,0,0,330877
"McCarthy, Mr. Timothy J",7,0,1,male,54.0,0,0,17463
"Palsson, Master. Gosta Leonard",8,0,3,male,2.0,3,1,349909
"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",9,1,3,female,27.0,0,2,347742
"Nasser, Mrs. Nicholas (Adele Achem)",10,1,2,female,14.0,1,0,237736

In [111]:
df['child'] = df['SibSp']+df['Parch']
print(df)

                                                    PassengerId  Survived  \
Name
Braund, Mr. Owen Harris                                       1         0
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1
Heikkinen, Miss. Laina                                        3         1
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1
Allen, Mr. William Henry                                      5         0
...                                                         ...       ...
Montvila, Rev. Juozas                                       887         0
Graham, Miss. Margaret Edith                                888         1
Johnston, Miss. Catherine Helen "Carrie"                    889         0
Behr, Mr. Karl Howell                                       890         1
Dooley, Mr. Patrick                                         891         0

                                                    Pclass     Sex   Age  \
Name
Braund, Mr. Owen Harris                                  3    male  22.0
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0
Heikkinen, Miss. Laina                                   3  female  26.0
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0
Allen, Mr. William Henry                                 3    male  35.0
...                                                    ...     ...   ...
Montvila, Rev. Juozas                                    2    male  27.0
Graham, Miss. Margaret Edith                             1  female  19.0
Johnston, Miss. Catherine Helen "Carrie"                 3  female   NaN
Behr, Mr. Karl Howell                                    1    male  26.0
Dooley, Mr. Patrick                                      3    male  32.0

                                                    SibSp  Parch  \
Name
Braund, Mr. Owen Harris                                 1      0
Cumings, Mrs. John Bradley (Florence Briggs Tha...      1      0
Heikkinen, Miss. Laina                                  0      0
Futrelle, Mrs. Jacques Heath (Lily May Peel)            1      0
Allen, Mr. William Henry                                0      0
...                                                   ...    ...
Montvila, Rev. Juozas                                   0      0
Graham, Miss. Margaret Edith                            0      0
Johnston, Miss. Catherine Helen "Carrie"                1      2
Behr, Mr. Karl Howell                                   0      0
Dooley, Mr. Patrick                                     0      0

                                                              Ticket     Fare  \
Name
Braund, Mr. Owen Harris                                    A/5 21171   7.2500
Cumings, Mrs. John Bradley (Florence Briggs Tha...          PC 17599  71.2833
Heikkinen, Miss. Laina                              STON/O2. 3101282   7.9250
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  113803  53.1000
Allen, Mr. William Henry                                      373450   8.0500
...                                                              ...      ...
Montvila, Rev. Juozas                                         211536  13.0000
Graham, Miss. Margaret Edith                                  112053  30.0000
Johnston, Miss. Catherine Helen "Carrie"                  W./C. 6607  23.4500
Behr, Mr. Karl Howell                                         111369  30.0000
Dooley, Mr. Patrick                                           370376   7.7500

                                                   Cabin Embarked  child
Name
Braund, Mr. Owen Harris                              NaN        S      1
Cumings, Mrs. John Bradley (Florence Briggs Tha...   C85        C      1
Heikkinen, Miss. Laina                               NaN        S      0
Futrelle, Mrs. Jacques Heath (Lily May Peel)        C123        S      1
Allen, Mr. William Henry                             NaN        S      0
...                                                  ...      ...    ...
Montvila, Rev. Juozas                                NaN        S      0
Graham, Miss. Margaret Edith                         B42        S      0
Johnston, Miss. Catherine Helen "Carrie"             NaN        S      3
Behr, Mr. Karl Howell                               C148        C      0
Dooley, Mr. Patrick                                  NaN        Q      0

[891 rows x 12 columns]

In [122]:
# Task
n = np.random.randint(1,100 , [8,5])
print(n)
ds = pd.DataFrame(n , columns=['A','B','C','D','E'])
print(ds)
print(ds.shape)
print(ds.size)
print(ds.ndim)

[[30 75 46 24 41]
 [66 12 95 73 80]
 [53 77 85 53 90]
 [12 60 66 36 18]
 [80 91 71 28 27]
 [45  2  6 30 89]
 [43 38 73 49 48]
 [45 16 59 24  8]]
    A   B   C   D   E
0  30  75  46  24  41
1  66  12  95  73  80
2  53  77  85  53  90
3  12  60  66  36  18
4  80  91  71  28  27
5  45   2   6  30  89
6  43  38  73  49  48
7  45  16  59  24   8
(8, 5)
40
2

In [125]:
ds['Sum'] = ds['A']+ds['B']+ds['C']+ds['D']+ds['E']
print(ds)

    A   B   C   D   E  Sum
0  30  75  46  24  41  216
1  66  12  95  73  80  326
2  53  77  85  53  90  358
3  12  60  66  36  18  192
4  80  91  71  28  27  297
5  45   2   6  30  89  172
6  43  38  73  49  48  251
7  45  16  59  24   8  152

In [127]:
ds.iloc[6,2]=56
print(ds)

    A   B   C   D   E  Sum
0  30  75  46  24  41  216
1  66  12  95  73  80  326
2  53  77  85  53  90  358
3  12  60  66  36  18  192
4  80  91  71  28  27  297
5  45   2   6  30  89  172
6  43  38  56  49  48  251
7  45  16  59  24   8  152

In [134]:
print(ds.iloc[2:8 , 1:4])
print(ds.loc[2:8 , 'B':'D'])

    B   C   D
2  77  85  53
3  60  66  36
4  91  71  28
5   2   6  30
6  38  56  49
7  16  59  24
    B   C   D
2  77  85  53
3  60  66  36
4  91  71  28
5   2   6  30
6  38  56  49
7  16  59  24

In [135]:
ds.loc['new']=[23 , 24 ,25, 26,27,28]
print(ds)

      A   B   C   D   E  Sum
0    30  75  46  24  41  216
1    66  12  95  73  80  326
2    53  77  85  53  90  358
3    12  60  66  36  18  192
4    80  91  71  28  27  297
5    45   2   6  30  89  172
6    43  38  56  49  48  251
7    45  16  59  24   8  152
new  23  24  25  26  27   28

In [136]:
d = np.random.randint(1,100 , [5,4])
df = pd.DataFrame(d , columns=['CourseID','CourseName','Credits','Faculty'])
print(df)

   CourseID  CourseName  Credits  Faculty
0        66          55       75       55
1        43          88       38       74
2        65          90       57       79
3        10          75        8       32
4        70           4       42       57

In [137]:
df = df.set_index('CourseID')
print(df)

          CourseName  Credits  Faculty
CourseID
66                55       75       55
43                88       38       74
65                90       57       79
10                75        8       32
70                 4       42       57

In [138]:
df['Semester'] = 1
print(df)

          CourseName  Credits  Faculty  Semester
CourseID
66                55       75       55         1
43                88       38       74         1
65                90       57       79         1
10                75        8       32         1
70                 4       42       57         1

In [139]:
df.iloc[1,1] = 35
print(df)

          CourseName  Credits  Faculty  Semester
CourseID
66                55       75       55         1
43                88       35       74         1
65                90       57       79         1
10                75        8       32         1
70                 4       42       57         1

In [140]:
df.loc['new']=[1,2,3,4]
print(df)

          CourseName  Credits  Faculty  Semester
CourseID
66                55       75       55         1
43                88       35       74         1
65                90       57       79         1
10                75        8       32         1
70                 4       42       57         1
new                1        2        3         4

In [141]:
t=pd.read_csv('train.csv')
print(t)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [142]:
t.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [143]:
t.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [145]:
t.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [146]:
t.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
794,795,0,3,"Dantcheff, Mr. Ristiu",male,25.0,0,0,349203,7.8958,NaN,S

In [147]:
t.sample(4)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
808,809,0,2,"Meyer, Mr. August",male,39.0,0,0,248723,13.0000,NaN,S
547,548,1,2,"Padro y Manent, Mr. Julian",male,NaN,0,0,SC/PARIS 2146,13.8625,NaN,C
498,499,0,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S
234,235,0,2,"Leyson, Mr. Robert William Norman",male,24.0,0,0,C.A. 29566,10.5000,NaN,S

In [148]:
t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [149]:
t.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [150]:
t.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Najib, Miss. Adele Kiamie ""Jane""",male,NaN,NaN,NaN,CA. 2343,NaN,C23 C25 C27,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN