In [1]:
import pandas as pd
import numpy as np

In [10]:
df = pd.DataFrame([[1 , np.nan , 3 , 4],[2 , 4, np.nan,8],[1,1,1,1],[np.nan,4,5,9],[np.nan,1,np.nan,3],[np.nan,np.nan,np.nan,np.nan]],columns=['A','B','C','D'])
print(df)

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  1.0  1.0  1.0  1.0
3  NaN  4.0  5.0  9.0
4  NaN  1.0  NaN  3.0
5  NaN  NaN  NaN  NaN

In [11]:
df

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  1.0  1.0  1.0  1.0
3  NaN  4.0  5.0  9.0
4  NaN  1.0  NaN  3.0
5  NaN  NaN  NaN  NaN

In [12]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False   True  False
2  False  False  False  False
3   True  False  False  False
4   True  False   True  False
5   True   True   True   True

In [14]:
df.isna().sum()

A    3
B    2
C    3
D    1
dtype: int64

In [17]:
# 0 row , 1 column
df.dropna(how='any',axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

In [18]:
df.dropna(how='any',axis=0)

     A    B    C    D
2  1.0  1.0  1.0  1.0

In [19]:
df.dropna(how='all',axis=0)

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  1.0  1.0  1.0  1.0
3  NaN  4.0  5.0  9.0
4  NaN  1.0  NaN  3.0

In [22]:
df.dropna(subset=['A'])

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  1.0  1.0  1.0  1.0

In [31]:
# any or , all and
df.dropna(subset=['B','D'] ,how='all')

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  1.0  1.0  1.0  1.0
3  NaN  4.0  5.0  9.0
4  NaN  1.0  NaN  3.0

In [32]:
df.dropna(thresh=2)

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  1.0  1.0  1.0  1.0
3  NaN  4.0  5.0  9.0
4  NaN  1.0  NaN  3.0

In [33]:
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  1.0  1.0  1.0  1.0
3  NaN  4.0  5.0  9.0

In [34]:
df.fillna(df.mean())

          A    B    C    D
0  1.000000  2.5  3.0  4.0
1  2.000000  4.0  3.0  8.0
2  1.000000  1.0  1.0  1.0
3  1.333333  4.0  5.0  9.0
4  1.333333  1.0  3.0  3.0
5  1.333333  2.5  3.0  5.0

In [35]:
df

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  1.0  1.0  1.0  1.0
3  NaN  4.0  5.0  9.0
4  NaN  1.0  NaN  3.0
5  NaN  NaN  NaN  NaN

In [44]:
df['A']=df['A'].fillna(df['A'].median())
df

     A    B    C    D
0  1.0  NaN  3.0  4.0
1  2.0  4.0  NaN  8.0
2  1.0  1.0  1.0  1.0
3  1.0  4.0  5.0  9.0
4  1.0  1.0  NaN  3.0
5  1.0  NaN  NaN  NaN