In [86]:
import pandas as pd
import numpy as np

In [117]:
df=pd.DataFrame(np.random.randint(1,100,(20,5)),columns=["A","B","C","D","E"])

In [118]:
df

     A   B   C   D   E
0   31  20  34  40  13
1   16  22  91  67  15
2    9  52  41  29  79
3   90  75  38  99  61
4   93  14  26  17   3
5   52  25  68  54  81
6   14  47  52  57  51
7   83  57  53  43  42
8   89   4  46  84   6
9   61  93  45  84  63
10  99   7  65  53  27
11  98  65  71  70  16
12  79  38  14  20  60
13  78  95  81  72  76
14  88   3  35  92  52
15  20  51  18  18  12
16  45  28  96  13  20
17  49  15  10  49  12
18  39  40  32  32  75
19  49  34  22  29  98

In [119]:
df.apply(sum)

A    1182
B     785
C     938
D    1022
E     862
dtype: int64

In [120]:
df.apply(sum,axis=1)

0     138
1     211
2     210
3     363
4     153
5     280
6     221
7     278
8     229
9     346
10    251
11    320
12    211
13    402
14    270
15    119
16    202
17    135
18    218
19    232
dtype: int64

In [121]:
df.apply("mean")

A    59.10
B    39.25
C    46.90
D    51.10
E    43.10
dtype: float64

In [122]:
df.apply(["mean",sum],axis=1)

    mean    sum
0   27.6  138.0
1   42.2  211.0
2   42.0  210.0
3   72.6  363.0
4   30.6  153.0
5   56.0  280.0
6   44.2  221.0
7   55.6  278.0
8   45.8  229.0
9   69.2  346.0
10  50.2  251.0
11  64.0  320.0
12  42.2  211.0
13  80.4  402.0
14  54.0  270.0
15  23.8  119.0
16  40.4  202.0
17  27.0  135.0
18  43.6  218.0
19  46.4  232.0

In [123]:
df.apply(lambda x:x["A"]+x["B"]+x["C"],axis=1)

0      85
1     129
2     102
3     203
4     133
5     145
6     113
7     193
8     139
9     199
10    171
11    234
12    131
13    254
14    126
15     89
16    169
17     74
18    111
19    105
dtype: int32

In [124]:
df["Total_Rowby"]=df.apply(sum,axis=1)

In [125]:
df

     A   B   C   D   E  Total_Rowby
0   31  20  34  40  13          138
1   16  22  91  67  15          211
2    9  52  41  29  79          210
3   90  75  38  99  61          363
4   93  14  26  17   3          153
5   52  25  68  54  81          280
6   14  47  52  57  51          221
7   83  57  53  43  42          278
8   89   4  46  84   6          229
9   61  93  45  84  63          346
10  99   7  65  53  27          251
11  98  65  71  70  16          320
12  79  38  14  20  60          211
13  78  95  81  72  76          402
14  88   3  35  92  52          270
15  20  51  18  18  12          119
16  45  28  96  13  20          202
17  49  15  10  49  12          135
18  39  40  32  32  75          218
19  49  34  22  29  98          232

In [126]:
def grade(x):
    if x>300:
        return "A+"
    if x>250:
        return "A"
    if x>200:
        return "B"
    return "F"

In [127]:
df["Grade"]=df["Total_Rowby"].apply(grade)

In [128]:
df

     A   B   C   D   E  Total_Rowby Grade
0   31  20  34  40  13          138     F
1   16  22  91  67  15          211     B
2    9  52  41  29  79          210     B
3   90  75  38  99  61          363    A+
4   93  14  26  17   3          153     F
5   52  25  68  54  81          280     A
6   14  47  52  57  51          221     B
7   83  57  53  43  42          278     A
8   89   4  46  84   6          229     B
9   61  93  45  84  63          346    A+
10  99   7  65  53  27          251     A
11  98  65  71  70  16          320    A+
12  79  38  14  20  60          211     B
13  78  95  81  72  76          402    A+
14  88   3  35  92  52          270     A
15  20  51  18  18  12          119     F
16  45  28  96  13  20          202     B
17  49  15  10  49  12          135     F
18  39  40  32  32  75          218     B
19  49  34  22  29  98          232     B

In [129]:
df.apply(lambda x:"Fail" if((x["A"]<35) or (x["B"]<35) or (x["C"]<35) or( x["D"]<35) or (x["E"]<35)) else "Pass",axis=1)

0     Fail
1     Fail
2     Fail
3     Pass
4     Fail
5     Fail
6     Fail
7     Pass
8     Fail
9     Pass
10    Fail
11    Fail
12    Fail
13    Pass
14    Fail
15    Fail
16    Fail
17    Fail
18    Fail
19    Fail
dtype: object

In [130]:
def res(x):
    if x["A"]<35 or x["B"]<35 or x["C"]<35 or x["D"]<35 or x["E"]<35:
        return "Fail"
    return "Pass"

In [131]:
df.apply(res,axis=1)

0     Fail
1     Fail
2     Fail
3     Pass
4     Fail
5     Fail
6     Fail
7     Pass
8     Fail
9     Pass
10    Fail
11    Fail
12    Fail
13    Pass
14    Fail
15    Fail
16    Fail
17    Fail
18    Fail
19    Fail
dtype: object

In [132]:
def bonus(y):
    return y+2

In [135]:
df["A"]=df["A"].apply(bonus)

In [136]:
df

      A   B   C   D   E  Total_Rowby Grade
0    33  20  34  40  13          138     F
1    18  22  91  67  15          211     B
2    11  52  41  29  79          210     B
3    92  75  38  99  61          363    A+
4    95  14  26  17   3          153     F
5    54  25  68  54  81          280     A
6    16  47  52  57  51          221     B
7    85  57  53  43  42          278     A
8    91   4  46  84   6          229     B
9    63  93  45  84  63          346    A+
10  101   7  65  53  27          251     A
11  100  65  71  70  16          320    A+
12   81  38  14  20  60          211     B
13   80  95  81  72  76          402    A+
14   90   3  35  92  52          270     A
15   22  51  18  18  12          119     F
16   47  28  96  13  20          202     B
17   51  15  10  49  12          135     F
18   41  40  32  32  75          218     B
19   51  34  22  29  98          232     B